[package]
name = "ruslin-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
any_ascii = "0.3.1"
async-trait = "0.1.59"
chrono = "0.4.23"
diesel = { version = "2.0", features = ["sqlite", "chrono", "r2d2", "uuid", "extras"] }
diesel_migrations = { version = "2.0", features = ["sqlite"] }
jieba-rs = "0.6.7"
log = "0.4.17"
parking_lot = "0.12.1"
porter-stemmer = "0.1.2"
r2d2 = "0.8.10"
# reqwest = { version = "0.11.13", features = ["json"] }
reqwest = { version = "0.11.13", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
serde_repr = "0.1.9"
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
unicode-normalization = "0.1.22"
unicode-segmentation = "1.10.0"
uuid = { version = "1.2.1", features = ["std", "v7"] }

[dev-dependencies]
env_logger = "0.10.0"
tempfile = "3.3.0"
toml = "0.5.9"

[patch.crates-io]
diesel = { git = 'https://github.com/DianQK/diesel.git', tag = "v2.0.2-p" }
