version: '3'

services:
    app:
        image: joplin/server:2.10.4-beta
        container_name: joplin-test-server
        ports:
            - "22300:22300"
        command: node dist/app.js --env dev
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=http://localhost:22300
            - JOPLIN_IS_TESTING=1
