[package]
name = "ruslin-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"

[dev-dependencies]
tempfile = "3.3.0"
